### ISSUE TITLE
Throw an error when putting the relative address constant offset on the wrong side

### ISSUE THREAD

**Issue by halcy** [devkitPro/picasso#24]
When using relative addressing, writing [1+a.x] results in the 1+ being silently ignored - this should probably be a syntax error instead, or do the same as [a.x+1].

**Comment by fincs** [comment]
Looks like I failed here:

https://github.com/fincs/picasso/blob/master/source/picasso_assembler.cpp#L719

Should have been `if (!*idxType)`.

Thanks for reporting, will fix at some point.

**Comment by Tilka** [comment]
ping
